### ISSUE TITLE
addTrack support?

### ISSUE THREAD

**Issue by ahmetozalp** [juncocoa/react-native-webrtc2#1]

**Comment by juncocoa** [comment]
@ahmetozalp yes, support addTrack

**Comment by ahmetozalp** [comment]
not working i try.

**Comment by ahmetozalp** [comment]
![Uploading Screen Shot 2020-09-30 at 10.05.48.png…]()

**Comment by ahmetozalp** [comment]
![Screen Shot 2020-09-30 at 10 05 48](https://user-images.githubusercontent.com/7665820/94653862-e617bd00-0304-11eb-92ac-0beacf7a3126.png)

**Comment by juncocoa** [comment]
@ahmetozalp Why can’t it work? Adding a track does not mean adding a transceiver. There is this difference

**Comment by ahmetozalp** [comment]
My English is not very good, am I not set up or not working? I am in the features I want

**Comment by ahmetozalp** [comment]
Can't this (https://github.com/juncocoa/react-native-webrtc2) package solve my problem?

simple-peer use.

      sender = this._pc.addTrack(track, stream)

https://github.com/feross/simple-peer/blob/0dd27ee83d615a8ff0eb48c49ed4917c9d6e2ff1/index.js#L286
